security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    role_hierarchy:
        ROLE_STAFF: ROLE_CLIENT_PRO
        ROLE_ADMIN: ROLE_STAFF

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        login:
            pattern: ^/api/auth/login
            stateless: true
            user_checker: App\Security\UtilisateurChecker
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UtilisateurChecker
            jwt: ~

    access_control:
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/mot-de-passe-oublie, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/reinitialisation, roles: PUBLIC_ACCESS }
        - { path: ^/api/utilisateurs, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_CLIENT_PRO }

when@test:
    security:
        password_hashers:
            App\Entity\Utilisateur:
                algorithm: bcrypt
                cost: 4
